# Generated by Django 5.1.4 on 2024-12-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('Id_Proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('Telefono', models.IntegerField()),
                ('Correo', models.CharField(max_length=100)),
                ('Ciudad', models.CharField(max_length=100)),
                ('Id_ProductoV', models.IntegerField()),
                ('PrecioProducto', models.IntegerField()),
                ('NombreProducto', models.CharField(max_length=300)),
            ],
        ),
    ]
